services:
  - type: web
    name: agentic-honey-pot-for-scam-detection
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: API_KEY
        value: team_recursives
      - key: CALLBACK_URL
        value: https://hackathon.guvi.in/api/updateHoneyPotFinalResult
      - key: MESSAGE_TIMEOUT_SECONDS
        value: 10
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
